In [1]:
source(here::here('MG3.functions1.R'))

# Writing species into the database

In [2]:
assembyfilename=paste0(StaticInpDir,"assemblies.json")
assembltext=readLines(assembyfilename)
assembliesJSON <- fromJSON(assembltext)

In [3]:
GenomesDF=NULL
for (assembly in assembliesJSON$reports ){
    row=list(accession=assembly$accession, sample= assembly$assembly_info$biosample$accession,
            taxon= assembly$assembly_info$biosample$description$organism$tax_id)
    if (is.null(row$taxon)){
        row$taxon=assembly$organism$tax_id
    }
    if (is.null(row$sample)){
        row$sample=NA
    }
    if (is.null(GenomesDF)){
        GenomesDF=as.data.frame(row)
    }else{
        GenomesDF=rbind(GenomesDF, as.data.frame(row))
    }
}

In [4]:
# run ONCE

if ("genomes" %in% dbListTables(mydbRW)) dbExecute(mydbRW, 'DROP TABLE genomes')
dbWriteTable(mydbRW, "genomes", GenomesDF, append=FALSE)

dbExecute(mydbRW, 'CREATE INDEX GenomesAccessionInd ON genomes(accession)')
dbExecute(mydbRW, 'CREATE INDEX GenomesTaxonInd ON genomes(taxon)')
dbExecute(mydbRW, 'CREATE INDEX GenomesSampleInd ON genomes(sample)')

[1] 0

[1] 0

[1] 0

# Saving chromosome lengths to SQLite

In [5]:
# run ONCE

if ("seqinfo" %in% dbListTables(mydbRW)) dbExecute(mydbRW, 'DROP TABLE seqinfo')

for (rowNumber in 1:nrow(GenomesDF)){
    if (rowNumber %% 20 == 0){
        message(rowNumber, "/", nrow(GenomesDF))
    }
    accession=GenomesDF$accession[rowNumber]
    #message(accession)
    chrsDF=getGenomeChrs(accession)
    #ID which CHR name format is used
    genomeDir=paste0(StaticInpDir, accession,"/")
    #message(genomeDir)
    fs=list.files(genomeDir, pattern = paste0(accession,".*_genomic.fna$"), full.names = TRUE)
    if (length(fs)!=1){
        message(accession)
        message(paste(accession, "PROBLEM"))
        break
    }
    firstLine=readLines(con = fs[1],n = 1)
    #message(firstLine)
    molname=str_extract(string = firstLine, pattern = "^>\\s*([^\\s]+)\\s+.*$", group = 1)
    #message(molname)
    colfound=FALSE
    for (cn in colnames(chrsDF)){
        if ( molname %in% chrsDF[[cn]]){
            #message(cn)
            colfound=TRUE
            break
        }
    }
    if (! colfound){
        message(accession)
        message(paste(accession, "COLUMN PROBLEM"))
        break
    }else{
       colnames(chrsDF)[colnames(chrsDF) == cn]="seqnames"
       colnames(chrsDF)[colnames(chrsDF) == "assemblyAccession"]="accession"
       colstoexport=c("accession", "seqnames", "chrName", "length")
       chrsDF$length=as.integer(chrsDF$length)
       dbWriteTable(mydbRW, "seqinfo", chrsDF[,colstoexport], append=TRUE)
        
    }
}

dbExecute(mydbRW, 'CREATE INDEX seqinfoAccessionSeqnamesInd ON seqinfo(accession,seqnames)')
dbExecute(mydbRW, 'CREATE INDEX seqinfoSeqnamesInd ON seqinfo(seqnames)')

20/223

40/223

60/223

80/223

100/223

120/223

140/223

160/223

180/223

200/223

220/223

[1] 0

[1] 0

In [6]:
length(unique(GenomesDF$taxon))

[1] 160

# Saving the GTFs

In [8]:
# Run ONCE
system(paste0("mkdir ", OutputDir,"/tmpGTF2CSV/slurm_logs/ -p" ), wait = TRUE) #creating the dir
if ("GTFs" %in% dbListTables(mydbRW)) dbExecute(mydbRW, 'DROP TABLE GTFs')
swarmparams=paste0("#SWARM -t 5 -g 10 --time=10:00:00 --gres=lscratch:10 --logdir ", fs::path_expand(paste0(OutputDir,"/tmpGTF2CSV/slurm_logs/")))
scriptname="~/data/lambda/notebooks/Rscript.wrapper.lambdaenv.sh"
swarmlines=c(swarmparams)

for (rowNumber in 1:nrow(GenomesDF)){
    accession = GenomesDF$accession[rowNumber]
    tmpline=paste(scriptname, "~/data/lambda/notebooks/importGTFsforStep02.r", accession)
    swarmlines=addToVec(swarmlines, tmpline)
}
fname=paste0(OutputDir,"tmpGTF2CSV/importGTFsToSQL-", getTimeStamp(),".swarm")
writeLines(text = swarmlines, con=fname)
message("resulting file: ", fname, " \n run it from bash")

resulting file: ~/data/lambda/output/tmpGTF2CSV/importGTFsToSQL-2026-01-13_18.16.32.605372.swarm
 run it from bash

In [33]:
#run ONCE
# importing CSVs to SQLite
if ("GTFs" %in% dbListTables(mydbRW)) dbExecute(mydbRW, 'DROP TABLE GTFs')
dbExecute(mydbRW, 'CREATE TABLE GTFs("bsid" TEXT, "seqnames" TEXT, "start" UNSIGNED BIG INT, "end" UNSIGNED BIG INT, "width" UNSIGNED BIG INT, "strand" TEXT, "source" TEXT, "type" TEXT, "gene" TEXT, "protein_id" TEXT, "Name" TEXT, "accession" TEXT)')
fs=list.files(paste0(OutputDir,"tmpGTF2CSV"), pattern = "*.csv$", full.names = TRUE)
for (f in fs){
    comToBash=sprintf('sqlite3 %s/%s -cmd ".mode csv" ".import %s GTFs" ".quit"', OutputDir, SQLfname,
                     fs::path_expand(f) )
    #message(comToBash)
    retval=system(comToBash, intern = TRUE, wait = TRUE)

}

[1] 0

In [34]:
# Run ONCE
dbExecute(mydbRW, "ALTER TABLE GTFs DROP COLUMN bsid")
dbExecute(mydbRW, "DELETE FROM GTFs WHERE GTFs.accession='accession'")
message("Cleanup")
dbExecute(mydbRW, 'CREATE INDEX GTFsAccGeneInd ON GTFs(accession,gene)')
message("Ind1")
dbExecute(mydbRW, 'CREATE INDEX GTFsMainCoordInd ON GTFs(accession,seqnames,start,end,strand)')
message("Ind2")
dbExecute(mydbRW, 'CREATE INDEX GTFsEndCoordInd ON GTFs(accession,seqnames,end,strand)')
message("Ind3")
dbExecute(mydbRW, 'CREATE INDEX GTFsNameInd ON GTFs(Name)')
message("Ind4")
dbExecute(mydbRW, 'CREATE INDEX GTFsAccNameInd ON GTFs(accession,Name)')
message("Ind5")
dbExecute(mydbRW, 'CREATE INDEX GTFsgeneInd ON GTFs(gene)')
message("Ind6")
dbExecute(mydbRW, 'CREATE INDEX GTFsAccProtInd ON GTFs(accession,protein_id)')
message("In7")
dbExecute(mydbRW, 'CREATE INDEX GTFsProtInd ON GTFs(protein_id)')
message("Ind8")
system("echo 1 > ~/data/lambda/output/doneGTFs", intern = TRUE, wait = TRUE)

[1] 0

[1] 183

Cleanup

[1] 0

Ind1

[1] 0

Ind2

[1] 0

Ind3

[1] 0

Ind4

[1] 0

Ind5

[1] 0

Ind6

[1] 0

In7

[1] 0

Ind8

character(0)

# Saving taxonomy to SQL

In [17]:
#run ONCE
if ("taxonomy" %in% dbListTables(mydbRW)) dbExecute(mydbRW, 'DROP TABLE taxonomy')

taxonomyList=classification(GenomesDF$taxon, db = 'ncbi')
taxonomyList2=lapply(X = taxonomyList, FUN=function(X){X$orderTax=1:nrow(X)
                                                      return(X)})
taxonomyDF=NULL
for ( i in 1:length(taxonomyList2)){
    accession=GenomesDF$accession[i]
    tmpDF=taxonomyList2[[i]]
    tmpDF$accession=accession
    taxonomyDF=addToDF(taxonomyDF, tmpDF)
}
dbWriteTable(mydbRW, "taxonomy", taxonomyDF, append=FALSE)

dbExecute(mydbRW, 'CREATE INDEX TaxonomyIdInd ON taxonomy(id)')
dbExecute(mydbRW, 'CREATE INDEX TaxonomyAccessionInd ON taxonomy(accession)')
dbExecute(mydbRW, 'CREATE INDEX TaxonomyAccessionOrderInd ON taxonomy(accession,orderTax)')

[1] 0

[1] 0

[1] 0

# Running RMSK

In [18]:
getGenomeChrs=function(inAccession){
    inFiname=paste0(StaticInpDir, inAccession, "/sequence_report.jsonl")
    inLines=readLines(inFiname)
    chrlens=as.integer(str_extract(string = inLines, pattern = ',\\s*"length"\\s*:\\s*(\\d+)\\s*,',group = 1 ))
    boolmask=(chrlens>=minCHrLim)
    boolmask[is.na(boolmask)]=FALSE
    goodLines=inLines[boolmask]
    thetext=paste0(goodLines, collapse = ",\n")

    thetext=paste0('{"assemblies": [',thetext,"]}")
    result <- fromJSON(thetext)
    outDF=NULL
    for (assembly in result$assemblies){
        if (is.null(outDF)){
            outDF=as.data.frame(assembly)
        }else{
            extracols=setdiff(colnames(outDF), names(assembly))
            for (cn in extracols){
                assembly[[cn]]=NA
            }
            extracols=setdiff(names(assembly), colnames(outDF))
            for (cn in extracols){
                outDF[[cn]]=NA
            }
            outDF=rbind(outDF, as.data.frame(assembly))
        }
    }
    return(outDF)
}

In [22]:
system(paste0("mkdir ", OutputDir,"/RMSK/slurm_logs/ -p" ), wait = TRUE) #creating the dir

sbatchscript="~/data/lambda/notebooks/Rscript.wrapper.lambdaenv.sh ~/data/lambda/notebooks/prepareChrFastaAndRun_NCBIrepeatMaskerChromosome.sh.R"
swarmlines=NULL #--time 10:00:00 --gres=lscratch:100 --mem=20g --cpus-per-task=5
for (rowNumber in 1:nrow(GenomesDF)){
    accession=GenomesDF$accession[rowNumber]
    
    chrsDF=getGenomeChrs(accession)
    #ID which CHR name format is used
    genomeDir=paste0(StaticInpDir, accession,"/")
    #message(genomeDir)
    fs=list.files(genomeDir, pattern = paste0(accession,".*_genomic.fna$"), full.names = TRUE)
    if (length(fs)!=1){
        message(accession)
        message(paste(accession, "PROBLEM"))
        break
    }
    firstLine=readLines(con = fs[1],n = 1)
    #message(firstLine)
    molname=str_extract(string = firstLine, pattern = "^>\\s*([^\\s]+)\\s+.*$", group = 1)
    #message(molname)
    colfound=FALSE
    for (cn in colnames(chrsDF)){
        if ( molname %in% chrsDF[[cn]]){
            #message(cn)
            colfound=TRUE
            break
        }
    }
    if (! colfound){
        message(accession)
        message(paste(accession, "COLUMN PROBLEM"))
        break
    }else{
        #message(cn)
        #add the sbatch call here
        #taxonID=getWorkingTaxonID(accession)#GenomesDF$taxon[rowNumber]
        for (chrname in chrsDF[[cn]]){
            #checking if 
            #comToBash=paste0("sbatch --time 10:00:00 --gres=lscratch:100 --mem=20g --cpus-per-task=5  ",sbatchscript," ",accession," ",chrname," ",taxonID," ~/data/lambda/multigene2/Genomes/ ~/data/lambda/multigene2/RMSK/")
            #system(comToBash, intern = FALSE, wait = FALSE)
            swarmline=paste0(sbatchscript," ",accession," ",chrname," ", OutputDir, "/RMSK/")
            swarmlines=addToVec(swarmlines, swarmline)
        }
    }
}

In [23]:
swarmlines[1:2]

[1] "~/data/lambda/notebooks/Rscript.wrapper.lambdaenv.sh ~/data/lambda/notebooks/prepareChrFastaAndRun_NCBIrepeatMaskerChromosome.sh.R GCF_027475565.1 NC_069380.1 ~/data/lambda/output//RMSK/"
[2] "~/data/lambda/notebooks/Rscript.wrapper.lambdaenv.sh ~/data/lambda/notebooks/prepareChrFastaAndRun_NCBIrepeatMaskerChromosome.sh.R GCF_027475565.1 NC_069382.1 ~/data/lambda/output//RMSK/"

In [27]:
#run ONCE
swarmparams=paste0("#SWARM -t 5 -g 20 --time=10:00:00 --gres=lscratch:100 --logdir ", path.expand(OutputDir),"/RMSK/slurm_logs/")
maxchunk=1000
timestamp=getTimeStamp()
processed=0
i=0
swarmFiles=NULL
while (processed<length(swarmlines)){
    upperlimit=processed+min(maxchunk, length(swarmlines)-processed)
    message(paste(processed+1, upperlimit))
    fname=paste0(OutputDir,"/RMSK/runningRMSKperCHR.",i,"-", getTimeStamp(),".swarm")
    writeLines(text = c(swarmparams, swarmlines[(processed+1):upperlimit]), 
               con=fname)
    swarmFiles=addToVec(swarmFiles, fname)
    #message("Run from bash: ", fname)
    processed=upperlimit
    i=i+1
}

1 1000

1001 2000

2001 3000

3001 4000

4001 5000

5001 6000

6001 7000

7001 7693

In [ ]:
#Run once
startedBool=rep(FALSE, length(swarmFiles))
while (!all(startedBool)){
    for (i in 1:length(swarmFiles)){
        if (!startedBool[i]){
            comToBash=paste0("swarm ", swarmFiles[i])
            message(comToBash)
            retval=system(comToBash, wait = TRUE)
            if (retval == 0){
                startedBool[i]=TRUE
                message("\t Success")
            }else{
                message("\t Nope")
                Sys.sleep(2)
            }
        }
    }
    if (!all(startedBool)){
        message(sum(!startedBool) ,"left")
        Sys.sleep(120)
    }
}
system('echo 1 > /home/frimanav/data/lambda/output/doneRMSKschedulting', intern = TRUE, wait = TRUE)

swarm ~/data/lambda/output//RMSK/runningRMSKperCHR.0-2026-01-13_18.48.56.239094.swarm

	 Success

swarm ~/data/lambda/output//RMSK/runningRMSKperCHR.1-2026-01-13_18.48.56.248132.swarm

	 Success

swarm ~/data/lambda/output//RMSK/runningRMSKperCHR.2-2026-01-13_18.48.56.284561.swarm

	 Success

swarm ~/data/lambda/output//RMSK/runningRMSKperCHR.3-2026-01-13_18.48.56.303986.swarm

	 Nope

swarm ~/data/lambda/output//RMSK/runningRMSKperCHR.4-2026-01-13_18.48.56.325485.swarm

	 Nope

swarm ~/data/lambda/output//RMSK/runningRMSKperCHR.5-2026-01-13_18.48.56.332126.swarm

	 Nope

swarm ~/data/lambda/output//RMSK/runningRMSKperCHR.6-2026-01-13_18.48.56.340563.swarm

	 Nope

swarm ~/data/lambda/output//RMSK/runningRMSKperCHR.7-2026-01-13_18.48.56.349169.swarm

	 Success

4left

## Checking if the work is done

In [13]:
# Checking completion of the repeatmasker run
minBEDfileSize=5000
problemChrsDF=NULL
for (rowNumber in 1:nrow(GenomesDF)){
    accession=GenomesDF$accession[rowNumber]
    if (rowNumber %% 10 == 0) message(rowNumber, '/', nrow(GenomesDF))
    chrsDF=getGenomeChrs(accession)
    #ID which CHR name format is used
    genomeDir=paste0(StaticInpDir, accession,"/")
    #message(genomeDir)
    fs=list.files(genomeDir, pattern = paste0(accession,".*_genomic.fna"), full.names = TRUE)
    
    if (length(fs)<1){
        message(accession)
        message(paste(accession, "PROBLEM"))
        break
    }
    largest_fasta_size=-1
    full_fasta_path=NULL
    for (fname in fs){
        if (file.info(fname)$size > largest_fasta_size){
            largest_fasta_size=file.info(fname)$size
            full_fasta_path=fname
        }
    }
    firstLine=readLines(con = full_fasta_path,n = 1)
    #message(firstLine)
    molname=str_extract(string = firstLine, pattern = "^>\\s*([^\\s]+)\\s+.*$", group = 1)
    #message(molname)
    colfound=FALSE
    for (cn in colnames(chrsDF)){
        if ( molname %in% chrsDF[[cn]]){
            #message(cn)
            colfound=TRUE
            break
        }
    }
    if (! colfound){
        message(accession)
        message(paste(accession, "COLUMN PROBLEM"))
        break
    }else{
        #message(cn)
        #Check if the bed file exists
        assemblyDir=paste0(StaticInpDir,accession)
        RMSKDir=paste0(OutputDir,"/RMSK/",accession)
        for (k in 1:length(chrsDF[[cn]])){
            chrname=chrsDF[[cn]][k]
            chrlen=chrsDF$length[k]
            if (chrlen < minCHrLim) next
            assemblyFiles=list.files(RMSKDir, pattern = paste0(accession,".*", chrname,".fna.repeatMasker.bed"), full.names = TRUE)
            if (length(assemblyFiles)!=1){
                tmpDF=data.frame(accession=accession, chr=chrname, chrlen=chrlen, nfiles=length(assemblyFiles))
                problemChrsDF=addToDF(problemChrsDF, tmpDF)
            }else{
                if (file.info(assemblyFiles)$size < minBEDfileSize){
                    tmpDF=data.frame(accession=accession, chr=chrname, chrlen=chrlen, nfiles=length(assemblyFiles), size=file.info(assemblyFiles)$size, numchrs=length(chrsDF[[cn]]))
                    problemChrsDF=addToDF(problemChrsDF, tmpDF)
                }
            }
        }
        #GCF_028885625.2_NHGRI_mPonPyg2-v2.0_pri_genomic.fna_NC_072395.2.fna.repeatMasker.bed
        
        
    }
    
}

10/223

20/223

30/223

40/223

50/223

60/223

70/223

80/223

90/223

100/223

110/223

120/223

130/223

140/223

150/223

160/223

170/223

180/223

190/223

200/223

210/223

220/223

In [14]:
problemChrsDF = as.data.frame( problemChrsDF %>% group_by(accession) %>% mutate(numproblem=n()))

In [25]:
problemChrsDF=problemChrsDF[ problemChrsDF$chrlen>lookaroundDist & is.na(problemChrsDF$size), ]

In [26]:
problemChrsDF

    accession       chr         chrlen     nfiles size numchrs numproblem
24  GCF_000003205.7 NC_007305.6  113155487 0      NA   NA       1
25  GCF_023091745.1 NC_068910.1  221681955 0      NA   NA      14
40  GCF_036321535.1 NC_087449.1   70542807 0      NA   NA      10
102 GCF_033118175.1 NC_083710.1   90020548 0      NA   NA      48
150 GCF_030445035.2 NC_080697.1   65148191 0      NA   NA       1
183 GCF_029281585.2 NC_073244.2   80312928 0      NA   NA       1
184 GCF_964656455.1 NC_135721.1  139080281 0      NA   NA       1
204 GCA_000230815.1 CM001276.1   232296185 0      NA   NA       1
205 GCF_049350105.2 NC_133406.1  240198992 0      NA   NA       1
206 GCF_003339765.1 NC_041760.1  169868564 0      NA   NA       1
213 GCF_025265405.1 NC_082664.1  184908288 0      NA   NA       1
214 GCA_008782695.1 CM018501.1  1107743563 0      NA   NA       1
221 GCF_020171115.1 NC_058097.1  207076058 0      NA   NA       4
247 GCA_017524585.1 CM029827.1    95403819 0      NA   NA       1
248 GCF_028858775.2 NC_072404.2  174648847 0      NA   NA       3
249 GCF_028858775.2 NC_072417.2   99595324 0      NA   NA       3
250 GCF_028858775.2 NC_072419.2   78115444 0      NA   NA       3
251 GCF_018350215.1 NC_056682.1  205061116 0      NA   NA       1
257 GCF_963924675.1 NC_089239.1   36425219 0      NA   NA       1
258 GCF_028885655.2 NC_085928.1  209544987 0      NA   NA       2
259 GCF_028885655.2 NC_071988.2  212916775 0      NA   NA       2
260 GCF_028885625.2 NC_072396.2  160969493 0      NA   NA       1
261 GCA_047655245.1 CM105557.1    80985033 0      NA   NA       1
306 GCF_024139225.1 NC_064851.1  168485645 0      NA   NA       1

### Trying to ID problem taxa (not needed. do not run)

In [27]:
system(paste0("mkdir ", OutputDir,"/RMSK/slurm_logs2/ -p" ), wait = TRUE) #creating the dir

sbatchscript="~/data/lambda/notebooks/Rscript.wrapper.lambdaenv.sh ~/data/lambda/notebooks/prepareChrFastaAndRun_NCBIrepeatMaskerChromosome.sh.R"
swarmlines2=NULL #--time 10:00:00 --gres=lscratch:100 --mem=20g --cpus-per-task=5
for (i in 1:nrow(problemChrsDF)){
    accession=problemChrsDF$accession[i]
    chrname=problemChrsDF$chr[i]
    swarmline=paste0(sbatchscript," ",accession," ",chrname," ", OutputDir, "/RMSK/")
    swarmlines2=addToVec(swarmlines2, swarmline)
}

In [28]:
length(swarmlines2)

[1] 24

In [32]:
swarmlines2[1:2]

[1] "~/data/lambda/notebooks/Rscript.wrapper.lambdaenv.sh ~/data/lambda/notebooks/prepareChrFastaAndRun_NCBIrepeatMaskerChromosome.sh.R GCF_000003205.7 NC_007305.6 ~/data/lambda/output//RMSK/"
[2] "~/data/lambda/notebooks/Rscript.wrapper.lambdaenv.sh ~/data/lambda/notebooks/prepareChrFastaAndRun_NCBIrepeatMaskerChromosome.sh.R GCF_023091745.1 NC_068910.1 ~/data/lambda/output//RMSK/"

In [30]:
#run ONCE
swarmparams=paste0("#SWARM -t 5 -g 30 --time=24:00:00 --gres=lscratch:150 --logdir ", path.expand(OutputDir),"/RMSK/slurm_logs2/")
maxchunk=1000
timestamp=getTimeStamp()
processed=0
i=0
swarmFiles=NULL
while (processed<length(swarmlines2)){
    upperlimit=processed+min(maxchunk, length(swarmlines2)-processed)
    message(paste(processed+1, upperlimit))
    fname=paste0(OutputDir,"/RMSK/runningRMSKperCHR_attempt2-.",i,"-", getTimeStamp(),".swarm")
    swarmFiles=addToVec(swarmFiles, fname)
    writeLines(text = c(swarmparams, swarmlines2[(processed+1):upperlimit]), 
               con=fname)
    #message("Run from bash: ", fname)
    processed=upperlimit
    i=i+1
}

1 24

In [31]:
startedBool=rep(FALSE, length(swarmFiles))
while (!all(startedBool)){
    for (i in 1:length(swarmFiles)){
        if (!startedBool[i]){
            comToBash=paste0("swarm ", swarmFiles[i])
            message(comToBash)
            retval=system(comToBash, wait = TRUE)
            if (retval == 0){
                startedBool[i]=TRUE
                message("\t Success")
            }else{
                message("\t Nope")
                Sys.sleep(2)
            }
        }
    }
    if (!all(startedBool)){
        message(sum(!startedBool) ,"left")
        Sys.sleep(120)
    }
}
system('echo 1 > /home/frimanav/data/lambda/output/doneRMSKschedulting-attempt2', intern = TRUE, wait = TRUE)

swarm ~/data/lambda/output//RMSK/runningRMSKperCHR_attempt2-.0-2026-01-14_12.48.57.365692.swarm

	 Success

character(0)

## Saving RMSK bed files to SQL

In [ ]:
#run ONCE


queryTxt='SELECT DISTINCT accession FROM seqinfo'
accessionsTMP=dbGetQuery(mydbRW, queryTxt)[["accession"]]
combinedRMSKdfList=list()
for (i in 1:length(accessionsTMP)){
    accession = accessionsTMP[i]
    if (i %% 10 == 0) message(paste(i,"/",length(accessionsTMP)))
    assemblyDir=paste0(OutputDir,"RMSK/",accession,"/")
    queryTxt=sprintf('SELECT DISTINCT seqnames FROM seqinfo WHERE accession="%s"', accession)
    chrNames=dbGetQuery(mydbRO, queryTxt)[["seqnames"]]
    for (chrname in chrNames){
        assemblyFiles=list.files(assemblyDir, pattern = paste0(accession,".*", chrname,".fna.repeatMasker.bed"), full.names = TRUE)
        if (length(assemblyFiles)==1){
            if (file.info(assemblyFiles)$size >= minBEDfileSize){
                tmpDF=read.table(file = assemblyFiles, sep = "\t", col.names = c("seqnames", "start", "end", "descr", "score", "strand"))
                tmpDF$score=NULL
                tmpCols=c("seqnames", "start", "end", "strand", "descr")
                tmpDF2=tmpDF[, tmpCols]
                tmpDF2$accession=accession
                tmpDF2$start=tmpDF2$start +1 #fixing the zero-based BED format
                tmpDF2=tmpDF2[tmpDF2$end - tmpDF2$start >= minRMSKinsertionlen,]
                if (nrow(tmpDF2)>0){
                    combinedRMSKdfList[[length(combinedRMSKdfList)+1]]=tmpDF2
                }
            }
        }else{
            message("Problem ", accession," ", chrname)
        }
    }
}

combinedRMSKdf=bind_rows(combinedRMSKdfList)

if ("RMSK" %in% dbListTables(mydbRW)) dbExecute(mydbRW, 'DROP TABLE RMSK')
dbWriteTable(mydbRW, "RMSK", combinedRMSKdf, append=FALSE)
message("Start indexing")
dbExecute(mydbRW, 'CREATE INDEX RMSKaccessionInd ON RMSK(accession)')
message("Ind 1")
dbExecute(mydbRW, 'CREATE INDEX RMSKaccessionSeqnamesInd ON RMSK(accession, seqnames)')
message("Ind 2")
dbExecute(mydbRW, 'CREATE INDEX RMSKSeqnamesInd ON RMSK(seqnames)')
message("Ind 3")
dbExecute(mydbRW, 'CREATE INDEX RMSKCoordInd ON RMSK(seqnames, start, end, strand)')
message("Ind 4")
dbExecute(mydbRW, 'CREATE INDEX RMSKAccessionCoordInd ON RMSK(accession, seqnames, start, end, strand)')
message("Ind 5")
system('echo 1 > /home/frimanav/data/lambda/output/doneRMSKsaving', intern = TRUE, wait = TRUE)

10 / 223

# check large chromosomes have RMSK

In [4]:
queryTxt=sprintf('SELECT * FROM seqinfo WHERE length > %d', 5e6)
longCHRsDF=dbGetQuery(mydbRO, queryTxt)

In [5]:
problemChrsDF2=NULL
for (accession in unique(longCHRsDF$accession)){
    subsetDF=longCHRsDF[ longCHRsDF$accession == accession, ]
    longchrnames=subsetDF$seqnames
    queryTxt=sprintf('SELECT DISTINCT seqnames FROM RMSK WHERE accession=="%s"', accession)
    rmskCHRsDFtmp=dbGetQuery(mydbRO, queryTxt)
    if ( !all(longchrnames %in% rmskCHRsDFtmp$seqnames)){
        message("Not all chrs of ", accession, " . Num found: ", sum(longchrnames %in% rmskCHRsDFtmp$seqnames),"/",length(longchrnames ))
        longestchr=max(subsetDF$length[! longchrnames %in% rmskCHRsDFtmp$seqnames])
        namelongest=subsetDF$chrName[ subsetDF$length==longestchr]
        message("\tLongest problem: ",longestchr)
        tmpDF=data.frame(accession=accession, chr=longchrnames[! longchrnames %in% rmskCHRsDFtmp$seqnames])
        problemChrsDF2=addToDF(problemChrsDF2, tmpDF)

    }
}

Not all chrs of GCF_036321535.1 . Num found: 43/44

	Longest problem: 5577944

Not all chrs of GCF_047675955.1 . Num found: 30/33

	Longest problem: 6591012

Not all chrs of GCF_033118175.1 . Num found: 54/55

	Longest problem: 5629527

Not all chrs of GCF_020826845.1 . Num found: 51/52

	Longest problem: 8065355

Not all chrs of GCF_028021215.1 . Num found: 24/25

	Longest problem: 12442647

Not all chrs of GCA_023701675.1 . Num found: 31/32

	Longest problem: 5592578

Not all chrs of GCF_028885655.2 . Num found: 24/25

	Longest problem: 212916775

In [6]:
problemChrsDF2

  accession       chr
1 GCF_036321535.1 NW_026989811.1
2 GCF_047675955.1 NW_027326745.1
3 GCF_047675955.1 NW_027327481.1
4 GCF_047675955.1 NW_027327592.1
5 GCF_033118175.1 NW_026870885.1
6 GCF_020826845.1 NW_026690854.1
7 GCF_028021215.1 NW_027175249.1
8 GCA_023701675.1 JALAIW010000029.1
9 GCF_028885655.2 NC_071988.2

In [ ]:
sbatchscript="~/data/lambda/notebooks/Rscript.wrapper.lambdaenv.sh ~/data/lambda/notebooks/prepareChrFastaAndRun_NCBIrepeatMaskerChromosome.sh.R"
swarmlines3=NULL 
for (rowNumber in 1:nrow(problemChrsDF2)){
    accession=problemChrsDF2$accession[rowNumber]
    chrname=problemChrsDF2$chr[rowNumber]
    #ID which CHR name format is used
    genomeDir=paste0(StaticInpDir, accession,"/")
    workingTaxon=NULL
    tmpTaxDF=getTaxonID(accession)  
    for (j in 1:max(5,nrow(tmpTaxDF))){
        taxIDtmp=tmpTaxDF$id[j]
        if (testRepeatMaskerDB(taxIDtmp)){
            workingTaxon=taxIDtmp
            break
        }
    }
    if (is.null(workingTaxon)){
        message("Cannot find working taxon: ", accession)
    }else{
        swarmline=paste0(sbatchscript," ",accession," ",chrname," ",workingTaxon, " ", OutputDir, "/RMSK/")
        swarmlines3=addToVec(swarmlines3, swarmline)
    }
}

In [ ]:
#run ONCE
swarmparams=paste0("#SWARM -t 10 -g 200 --time=48:00:00 --gres=lscratch:500 --logdir ", path.expand(OutputDir),"/slurm_logs/")
maxchunk=1000
timestamp=getTimeStamp()
processed=0
i=0
swarmFiles=NULL
while (processed<length(swarmlines3)){
    upperlimit=processed+min(maxchunk, length(swarmlines3)-processed)
    message(paste(processed+1, upperlimit))
    fname=paste0(OutputDir,"/RMSK/runningRMSKperCHR_attempt3-.",i,"-", getTimeStamp(),".swarm")
    swarmFiles=addToVec(swarmFiles, fname)
    writeLines(text = c(swarmparams, swarmlines3[(processed+1):upperlimit]), 
               con=fname)
    message("Run from bash: ", fname)
    processed=upperlimit
    i=i+1
}

In [ ]:
tmpTaxDF

# Making a list of TE coding genes wrongfully annotated in the host genomes

In [35]:
# run ONCE
i=0
tmpDir=paste0(OutputDir,"filteroutTEgenes/")
system(paste0("mkdir ", tmpDir, " -p"), wait=TRUE)
for (accession in GenomesDF$accession){
    if (i %% 10 == 0) message(i, " / ", length(GenomesDF$accession))
    proteinFA=paste0(StaticInpDir,"/", accession, "/protein.faa")    
    jobName=sprintf("InterPro.%s", accession)
    comToBash=sprintf("ml interproscan/5.72-103.0; cd %s ; interproscan --applications PANTHER,Pfam %s %s 1000; cd %s/%s ; sbatch interproscan.batch", tmpDir, proteinFA, jobName, tmpDir,jobName)
    queued_success=FALSE
    while (!queued_success){
        retval=system(comToBash, intern = FALSE, wait = TRUE)
        if (retval == 0){
            queued_success=TRUE
        }else{
            message("Sleeping i=",i," accession=",accession)
            Sys.sleep(60)
        }
    }
    
    i=i+1
}

0 / 223

10 / 223

20 / 223

30 / 223

40 / 223

50 / 223

60 / 223

70 / 223

Sleeping i=76 accession=GCF_029281585.2

Sleeping i=76 accession=GCF_029281585.2

Sleeping i=76 accession=GCF_029281585.2

Sleeping i=76 accession=GCF_029281585.2

Sleeping i=76 accession=GCF_029281585.2

Sleeping i=76 accession=GCF_029281585.2

Sleeping i=76 accession=GCF_029281585.2

Sleeping i=77 accession=GCF_000151905.2

Sleeping i=78 accession=GCF_008122165.1

80 / 223

Sleeping i=80 accession=GCF_030028045.1

Sleeping i=81 accession=GCF_000001405.40

Sleeping i=81 accession=GCF_000001405.40

Sleeping i=81 accession=GCF_000001405.40

Sleeping i=82 accession=GCF_000002125.1

Sleeping i=83 accession=GCF_000306695.2

Sleeping i=83 accession=GCF_000306695.2

Sleeping i=84 accession=GCF_009914755.1

Sleeping i=84 accession=GCF_009914755.1

Sleeping i=84 accession=GCF_009914755.1

Sleeping i=84 accession=GCF_009914755.1

Sleeping i=84 accession=GCF_009914755.1

Sleeping i=84 accession=GCF_009914755.1

Sleeping i=85 accession=GCA_011064465.2

Sleeping i=85 accession=GCA_011064465.2

Sleeping i=86 accession=GCA_018873775.2

Sleeping i=87 accession=GCA_022833125.2

Sleeping i=87 accession=GCA_022833125.2

Sleeping i=88 accession=GCF_052094955.1

Sleeping i=89 accession=GCF_016881025.1

90 / 223

Sleeping i=90 accession=GCA_016881025.1

Sleeping i=91 accession=GCF_020740685.1

Sleeping i=91 accession=GCF_020740685.1

Sleeping i=92 accession=GCF_026419965.1

Sleeping i=92 accession=GCF_026419965.1

Sleeping i=92 accession=GCF_026419965.1

Sleeping i=93 accession=GCF_949774975.1

Sleeping i=93 accession=GCF_949774975.1

Sleeping i=93 accession=GCF_949774975.1

Sleeping i=94 accession=GCF_020740605.2

Sleeping i=94 accession=GCF_020740605.2

Sleeping i=95 accession=GCF_018350155.1

Sleeping i=95 accession=GCF_018350155.1

Sleeping i=96 accession=GCF_033115175.1

Sleeping i=97 accession=GCF_030014295.1

Sleeping i=97 accession=GCF_030014295.1

Sleeping i=97 accession=GCF_030014295.1

Sleeping i=97 accession=GCF_030014295.1

Sleeping i=98 accession=GCF_902655055.1

Sleeping i=99 accession=GCF_007474595.2

100 / 223

Sleeping i=100 accession=GCF_037993035.2

Sleeping i=100 accession=GCF_037993035.2

Sleeping i=100 accession=GCF_037993035.2

Sleeping i=102 accession=GCF_012559485.2

Sleeping i=102 accession=GCF_012559485.2

Sleeping i=104 accession=GCF_049350105.2

Sleeping i=104 accession=GCF_049350105.2

Sleeping i=104 accession=GCF_049350105.2

Sleeping i=105 accession=GCF_000002255.3

Sleeping i=106 accession=GCF_000772875.2

Sleeping i=106 accession=GCF_000772875.2

Sleeping i=107 accession=GCF_003339765.1

Sleeping i=108 accession=GCA_000230795.1

Sleeping i=109 accession=GCF_043159975.1

110 / 223

Sleeping i=110 accession=GCF_024542745.1

Sleeping i=111 accession=GCF_040802235.1

Sleeping i=112 accession=GCF_030020395.1

Sleeping i=112 accession=GCF_030020395.1

Sleeping i=114 accession=GCF_008632895.1

Sleeping i=115 accession=GCF_922984935.1

Sleeping i=115 accession=GCF_922984935.1

Sleeping i=116 accession=GCF_030254825.1

Sleeping i=116 accession=GCF_030254825.1

Sleeping i=117 accession=GCF_025265405.1

Sleeping i=117 accession=GCF_025265405.1

Sleeping i=118 accession=GCF_040939455.1

Sleeping i=118 accession=GCF_040939455.1

Sleeping i=118 accession=GCF_040939455.1

Sleeping i=119 accession=GCF_000165445.2

Sleeping i=119 accession=GCF_000165445.2

Sleeping i=119 accession=GCF_000165445.2

120 / 223

Sleeping i=120 accession=GCF_000317375.1

Sleeping i=121 accession=GCF_037038515.1

Sleeping i=122 accession=GCF_021288785.2

Sleeping i=124 accession=GCF_963930625.1

Sleeping i=124 accession=GCF_963930625.1

Sleeping i=126 accession=GCF_900094665.2

Sleeping i=127 accession=GCF_000001635.27

Sleeping i=127 accession=GCF_000001635.27

Sleeping i=128 accession=GCF_900095145.1

Sleeping i=129 accession=GCF_009829155.1

Sleeping i=129 accession=GCF_009829155.1

Sleeping i=129 accession=GCF_009829155.1

130 / 223

Sleeping i=130 accession=GCF_030435805.1

Sleeping i=130 accession=GCF_030435805.1

Sleeping i=130 accession=GCF_030435805.1

Sleeping i=131 accession=GCF_022355385.1

Sleeping i=132 accession=GCF_963259705.1

Sleeping i=133 accession=GCA_047834645.1

Sleeping i=134 accession=GCF_028018385.1

Sleeping i=135 accession=GCF_020171115.1

Sleeping i=136 accession=GCF_002201575.2

Sleeping i=137 accession=GCF_006542625.1

Sleeping i=138 accession=GCF_000146795.2

Sleeping i=139 accession=GCF_027406575.1

140 / 223

Sleeping i=140 accession=GCF_030435755.1

Sleeping i=141 accession=GCF_014633375.1

Sleeping i=142 accession=GCF_023699985.2

Sleeping i=143 accession=GCF_903995425.1

Sleeping i=143 accession=GCF_903995425.1

Sleeping i=144 accession=GCF_937001465.1

Sleeping i=144 accession=GCF_937001465.1

Sleeping i=145 accession=GCF_964237555.1

Sleeping i=146 accession=GCF_000003625.3

Sleeping i=147 accession=GCF_009806435.1

Sleeping i=149 accession=GCA_023701675.1

150 / 223

Sleeping i=151 accession=GCF_016772045.2

Sleeping i=151 accession=GCF_016772045.2

Sleeping i=152 accession=GCF_000298735.2

Sleeping i=153 accession=GCF_002742125.1

Sleeping i=156 accession=GCA_041121725.1

Sleeping i=157 accession=GCF_042477335.2

Sleeping i=158 accession=GCF_029289425.2

Sleeping i=159 accession=GCF_000258655.2

Sleeping i=159 accession=GCF_000258655.2

160 / 223

Sleeping i=160 accession=GCF_028858775.2

Sleeping i=161 accession=GCF_000001515.7

Sleeping i=162 accession=GCF_002880755.1

Sleeping i=162 accession=GCF_002880755.1

Sleeping i=162 accession=GCF_002880755.1

Sleeping i=163 accession=GCA_002880755.3

Sleeping i=163 accession=GCA_002880755.3

Sleeping i=163 accession=GCA_002880755.3

Sleeping i=164 accession=GCF_018350215.1

Sleeping i=165 accession=GCF_028533385.1

Sleeping i=166 accession=GCF_018350195.1

Sleeping i=167 accession=GCF_023721935.1

Sleeping i=168 accession=GCF_008728515.1

Sleeping i=169 accession=GCF_000264685.3

Sleeping i=169 accession=GCF_000264685.3

170 / 223

Sleeping i=170 accession=GCF_023159225.1

Sleeping i=172 accession=GCF_004664715.2

Sleeping i=172 accession=GCF_004664715.2

Sleeping i=173 accession=GCF_049852395.1

Sleeping i=174 accession=GCF_003704035.1

Sleeping i=174 accession=GCF_003704035.1

Sleeping i=175 accession=GCF_016906955.1

Sleeping i=177 accession=GCF_008692025.1

Sleeping i=178 accession=GCF_004126475.2

Sleeping i=179 accession=GCF_002837175.3

180 / 223

Sleeping i=180 accession=GCF_002776525.5

Sleeping i=181 accession=GCA_963693515.1

Sleeping i=182 accession=GCA_040437455.1

Sleeping i=183 accession=GCF_028885655.2

Sleeping i=184 accession=GCF_002880775.1

Sleeping i=184 accession=GCF_002880775.1

Sleeping i=185 accession=GCA_002880775.3

Sleeping i=185 accession=GCA_002880775.3

Sleeping i=186 accession=GCF_028885625.2

Sleeping i=187 accession=GCF_016509475.1

Sleeping i=188 accession=GCF_022837055.1

Sleeping i=189 accession=GCF_039906515.1

Sleeping i=189 accession=GCF_039906515.1

190 / 223

Sleeping i=191 accession=GCA_949782905.1

Sleeping i=193 accession=GCF_036323735.1

Sleeping i=193 accession=GCF_036323735.1

Sleeping i=193 accession=GCF_036323735.1

Sleeping i=195 accession=GCF_000002265.2

Sleeping i=196 accession=GCF_015227675.2

Sleeping i=197 accession=GCA_000002265.1

Sleeping i=199 accession=GCF_004115265.2

Sleeping i=199 accession=GCF_004115265.2

200 / 223

Sleeping i=200 accession=GCF_036562045.2

Sleeping i=201 accession=GCF_007565055.1

Sleeping i=202 accession=GCF_036850765.1

Sleeping i=203 accession=GCF_036850995.1

Sleeping i=205 accession=GCF_048565385.1

Sleeping i=206 accession=GCF_902686445.1

Sleeping i=207 accession=GCA_041721565.1

Sleeping i=208 accession=GCF_027595985.1

210 / 223

Sleeping i=210 accession=GCF_006229205.1

Sleeping i=211 accession=GCF_000003025.6

Sleeping i=212 accession=GCF_028878055.3

Sleeping i=212 accession=GCF_028878055.3

Sleeping i=213 accession=GCF_023851605.1

Sleeping i=213 accession=GCF_023851605.1

Sleeping i=215 accession=GCF_003255815.1

Sleeping i=216 accession=GCF_011762595.2

Sleeping i=217 accession=GCF_045843805.1

Sleeping i=218 accession=GCF_023065955.2

Sleeping i=219 accession=GCF_048564905.1

Sleeping i=219 accession=GCF_048564905.1

220 / 223

Sleeping i=221 accession=GCF_048418805.1

Sleeping i=222 accession=GCF_009762305.2

Sleeping i=222 accession=GCF_009762305.2

In [38]:
system('echo 1 > /home/frimanav/data/lambda/output/doneinterproscanscheduling', intern = TRUE, wait = TRUE)

character(0)

## Get the list of signatures corresponding to TE proteins

In [4]:
# using TSV files exported from https://www.ebi.ac.uk/interpro/search/text/retroviral/#table
# for search queries "retrovirus", "retroviral", "transpos"
fs=list.files(path = StaticInpDir, pattern = "SearchResults.*tsv", full.names = TRUE)
TEsignaturesToFilterOut=NULL
for (f in fs){
    message(f)
    tmpDF=read.table(f, quote = '"', header=TRUE, sep="\t")
    TEsignaturesToFilterOut=addToDF(TEsignaturesToFilterOut, tmpDF)
}
TEsignaturesToFilterOutDBG=TEsignaturesToFilterOut

# InterPro adds a lot of BS. Double check the key words
keywords=c("trans", "retro")
NoBSbooleanMask=rep(FALSE, nrow(TEsignaturesToFilterOut))
for (keyw in keywords){
    NoBSbooleanMask = NoBSbooleanMask | grepl(pattern = keyw, x = TEsignaturesToFilterOut$Name, ignore.case = TRUE)
    NoBSbooleanMask = NoBSbooleanMask | grepl(pattern = keyw, x = TEsignaturesToFilterOut$Description, ignore.case = TRUE)

}
TEsignaturesToFilterOut=TEsignaturesToFilterOut[NoBSbooleanMask , ]


# InterPro adds a lot of BS. Double check the key words
keywords=c("domain([^s]|$)", "Zinc", "Eukaryot", "KINASE", "FACTOR") # negative KW
NoBSbooleanMask2=rep(FALSE, nrow(TEsignaturesToFilterOut))
for (keyw in keywords){
    NoBSbooleanMask2 = NoBSbooleanMask2 | grepl(pattern = keyw, x = TEsignaturesToFilterOut$Name, ignore.case = TRUE)
    NoBSbooleanMask2 = NoBSbooleanMask2 | grepl(pattern = keyw, x = TEsignaturesToFilterOut$Description, ignore.case = TRUE)

}
TEsignaturesToFilterOut=TEsignaturesToFilterOut[!NoBSbooleanMask2 , ]


NeedBooleanMask= TEsignaturesToFilterOut$Source.Database=="PANTHER"
NeedBooleanMask= NeedBooleanMask | TEsignaturesToFilterOut$Source.Database=="PFAM"
NeedBooleanMask= NeedBooleanMask | grepl(pattern = "polyprotein", x = TEsignaturesToFilterOut$Name, ignore.case = TRUE)
#NeedBooleanMask= NeedBooleanMask | grepl(pattern = "polyprotein", x = TEsignaturesToFilterOut$Description, ignore.case = TRUE)
NeedBooleanMask= NeedBooleanMask | grepl(pattern = "poly-protein", x = TEsignaturesToFilterOut$Name, ignore.case = TRUE)
#NeedBooleanMask= NeedBooleanMask | grepl(pattern = "poly-protein", x = TEsignaturesToFilterOut$Description, ignore.case = TRUE)

TEsignaturesToFilterOut=TEsignaturesToFilterOut[ NeedBooleanMask ,]

/home/frimanav/data/lambda/data//SearchResults-retroviral.tsv

/home/frimanav/data/lambda/data//SearchResultsretrovirus.tsv

/home/frimanav/data/lambda/data//SearchResultstranspos.tsv

In [5]:
nrow(TEsignaturesToFilterOut)

[1] 48

## Reading list of signatures found by interproscan in the genomes

In [6]:
getMaxDigitString=function(inElems){
    #message(typeof(inElems))
    #message(length(inElems))
    maxStringLen=0
    for (inStr in inElems){
        maxStringLen=max(maxStringLen, str_length(inStr))
    }
    return(maxStringLen)
}
getMaxDigitStringVector=function(inStrings){
    outVals=unlist(lapply(str_extract_all(string = inStrings, pattern = "[0-9]+"), FUN = getMaxDigitString))
    return(outVals)
}

In [7]:
TEprotResultsDirs=list.dirs(path = paste0(OutputDir, "filteroutTEgenes"), full.names = TRUE, recursive = FALSE)
TEprotResultsDirs=TEprotResultsDirs[ grepl(pattern = "InterPro\\.G.*", x = TEprotResultsDirs)]

In [8]:
DFtoWrite=NULL
for (i in 1:length(TEprotResultsDirs)){
    TEprotResultsDir = TEprotResultsDirs[i]
    accession=str_remove(string = basename(TEprotResultsDir), pattern = "InterPro.")
    # counting length of digit only sequences in gene names
    queryTxt=sprintf('SELECT DISTINCT gene FROM GTFs WHERE accession="%s" AND type="CDS"',
                     accession)
    genenames=dbGetQuery(mydbRO, queryTxt)[[1]]
    if (any(genenames=="?")){
        queryTxt=sprintf('SELECT DISTINCT Name FROM GTFs WHERE accession="%s" AND type="CDS"',
                     accession)
        genenames=dbGetQuery(mydbRO, queryTxt)[[1]]
    }
    numDigitsInRow=getMaxDigitStringVector(genenames)
    DigitisInRowThreshold = 4*median(numDigitsInRow)
    genenames.ManyDigits=genenames[ numDigitsInRow > DigitisInRowThreshold]
    
    # reading the InterPro outputs
    TSVfiles=list.files(path = TEprotResultsDir, pattern = "protein.*.tsv", full.names = TRUE)
    badGeneSuspects=NULL
    for ( f in TSVfiles ){
        tmpDF=read.table(f, quote = '"', header=FALSE, sep="\t")
        tmpDF=tmpDF[tmpDF$V5 %in% TEsignaturesToFilterOut$Accession , ]
        badGeneSuspects=addToDF(badGeneSuspects, tmpDF)
    
    }
    #print(badGeneSuspects)
    susGeneNames=NULL
    for (proteinID in badGeneSuspects$V1){
        tmpGeneDF=requestGTFbyProteinName(accession, proteinID)
        susGeneNamesTMP=unique(tmpGeneDF$gene)
        if (any(susGeneNames=="?")){
            susGeneNamesTMP=unique(tmpGeneDF$Name)
        }
        susGeneNames=addToVec(susGeneNames, susGeneNamesTMP)
    }
    
    susGeneNamesDigitsRows=getMaxDigitStringVector(susGeneNames)
    namesToRemoveFinal=unique(susGeneNames[ susGeneNamesDigitsRows> DigitisInRowThreshold])
    if (length(namesToRemoveFinal)>0){
        DFtoWriteTMP=data.frame(accession=accession, gene=namesToRemoveFinal)
        DFtoWrite=addToDF(DFtoWrite, DFtoWriteTMP)
        message(accession, ": ", paste0(namesToRemoveFinal, collapse = ", "))
    }else{
        if (i %% 20 == 0){
            message(accession,": ",i," / ", length(TEprotResultsDirs))
        }
    }
}

GCA_000003055.5: LOC100139216, LOC790428, LOC100139382, LOC100138743, LOC100336486, LOC786328, LOC100298055, LOC100295414, LOC781470, LOC100138700, LOC100296151, LOC100140993, LOC100297662, LOC100336014, LOC100299483, LOC100140931, LOC100138733, LOC100336391, LOC100335809

GCA_028583565.1: 20 / 223

GCF_000001895.5: LOC100363193, LOC102549694, LOC102551518, LOC102550650, LOC102553405, LOC102554594, LOC102555474, LOC102551620, LOC102555858, LOC102556213, LOC102555760, LOC102550241, LOC102546456, LOC102547206, LOC102551754, LOC103690189, LOC102550309, LOC102550582, LOC102546424, LOC103690834, LOC102555330, LOC103694538, LOC102552860, LOC102555832, LOC108349832, LOC108349608, LOC108349754, LOC108349573, LOC108349777, LOC108349732, LOC108349537, LOC108348438, LOC108349748, LOC108349511, LOC108349568, LOC108349495, LOC108349842, LOC108349865, LOC108349459, LOC108350189, LOC102551838, LOC108350002, LOC108349907, LOC108350249, LOC103691841, LOC102551194, LOC102552784, LOC103691918, LOC108350558, LOC108350747, LOC108350811, LOC108351267, LOC102547431, LOC108351076, LOC108351090, LOC108351339, LOC108351379, LOC108351583, LOC108351431, LOC108351410, LOC102556703, LOC108351491, LOC108351613, LOC108351581, LOC108351574, LOC108351576, LOC102554988, LOC108351873, LOC108351813, LOC108351836, LOC108351667, LOC108352370, LOC103690884, LOC108352495, LOC108352427, LOC108352635, LOC108352634, LOC108352613, LOC102556989, LOC108352515, LOC108352632, LOC108352748, LOC108352639, LOC102556672, LOC108352618, LOC102546505, LOC102553620, LOC102556474, LOC108352965, LOC103693664, LOC108353041, LOC102552169, LOC108353251, LOC108348812, LOC102555942, LOC108353264, LOC108353315, LOC108353314, LOC102557190, LOC103694571, LOC108349143, LOC102553611, LOC108353270, LOC108353410, LOC108353429, LOC108353265, LOC108349185, LOC108353287, LOC108349232, LOC103690842, LOC108349109, LOC108353281, LOC102556957

GCF_000002265.2: LOC100363193, LOC102556672, LOC102556813, LOC102552367, LOC103690884, LOC102556975, LOC103690842, LOC103690834, LOC102556957, LOC102551518, LOC102556827, LOC102555832, LOC102547825, LOC103693664, LOC108348433, LOC102556703, LOC108348438, LOC102550066, LOC102557044, LOC102547431, LOC108349191, LOC103694963, LOC108348812, LOC102548781, LOC108349459, LOC108349135, LOC108349109, LOC108349232, LOC108349352, LOC108349185, LOC108349147, LOC102556734, LOC102557190, LOC102546672, LOC108349143, LOC103695231, LOC108353491, LOC102555241, LOC108350918, LOC103691841, LOC108351034, LOC108350249, LOC108350811, LOC108350189, LOC108351123, LOC108353466, LOC108351267, LOC108353578, LOC102556859, LOC102554988, LOC108351410, LOC102549694, LOC108351613, LOC108353738, LOC108352613, LOC102556989, LOC108353715, LOC108353765, LOC108353747, LOC102555316, LOC108353706, LOC108352639, LOC108353734, LOC108353753, LOC108349511, LOC108352635, LOC108353741, LOC108353737, LOC108352618

GCF_000002285.5: LOC111093267, LOC111095618, LOC100688839, LOC487250, LOC102155235, LOC111091420, LOC111092249, LOC119870337, LOC102151787, LOC106558385, LOC102154491, LOC119870482, LOC119871300, LOC119874838, LOC102151484, LOC106558846, LOC119877895, LOC119872662, LOC119874041, LOC106559386, LOC119874017, LOC111097969, LOC119874254

GCF_000002305.2: LOC106780975, LOC106781368, LOC106781038, LOC106781350, LOC106782067, LOC106782942, LOC106783145, LOC106783143, LOC106783146, LOC106783142, LOC106783144

GCF_000003025.6: LOC106505794, LOC106510322, LOC106506534, LOC110255823, LOC110256025, LOC110256218, LOC106505804, LOC110256649, LOC110256914, LOC110256933, LOC102160003, LOC110257477, LOC102158723, LOC106510029, LOC102159737, LOC110258635, LOC110259374, LOC110259514, LOC102165146, LOC110261948, LOC106504658

GCF_000003055.6: LOC100848171, LOC100848463, LOC101906051, LOC104970693, LOC104972647, LOC104972492, LOC104973030, LOC104973175, LOC101903487, LOC104975936, LOC107131455, LOC107131654, LOC101906965, LOC107132073, LOC107132048, LOC107131927, LOC100138479, LOC107132074, LOC107132283, LOC104970269, LOC104972713, LOC107132544, LOC107132708, LOC101909710, LOC104969678, LOC107132899, LOC104974340

GCF_000003205.7: LOC100848171, LOC101906051, LOC101906965, LOC104974340, LOC104973175, LOC104973030, LOC104970693, LOC104972492, LOC107132283, LOC104970269, LOC104972647, LOC104972713, LOC107132544, LOC107132708, LOC101909710, LOC104969678, LOC107132899, LOC107131455, LOC101903487, LOC104976722, LOC107133373, LOC107131654, LOC107133390, LOC107131927, LOC104975936, LOC100138479, LOC107133408, LOC100848463, LOC107132073, LOC107132048, LOC107132074

GCF_000003625.3: LOC100351960, LOC103345092, LOC103345965, LOC103346967, LOC103347227, LOC103351067, LOC103351245, LOC100347275, LOC100352200, LOC103351755, LOC103345324, LOC108175790, LOC108175591, LOC108175598, LOC108175969, LOC108175995, LOC108176102, LOC108176213, LOC108176200, LOC103346449, LOC108176401, LOC100339296, LOC108176343, LOC108176831, LOC108176921, LOC100356118, LOC108177361, LOC108177250, LOC108177351, LOC108177450, LOC108177245, LOC108177900, LOC108178053, LOC108177899, LOC108177987, LOC108178042, LOC108178319, LOC103351068, LOC103351040, LOC108178205, LOC103350567, LOC108178473, LOC108178565, LOC108178448, LOC108178439, LOC108178716, LOC108178828, LOC108178691, LOC108178706, LOC108178888

GCF_000004665.1: LOC100390128, LOC103791282, LOC108588002, LOC108588451, LOC108588247, LOC108589691, LOC108589973, LOC108590109, LOC108590416, LOC100894730, LOC103791192, LOC108591043, LOC108592254, LOC108592807, LOC108592828, LOC108593366, LOC103795612, LOC103795804

GCF_000146795.2: LOC100603699

GCF_000151905.2: LOC109028578

GCF_000165445.2: LOC105857762, LOC105860015, LOC105861040, LOC105863875, LOC105865222, LOC105867148, LOC105867662, LOC105869582, LOC105874412, LOC105878335, LOC109729283, LOC109730230, LOC109730287, LOC105874833, LOC109731149, LOC109731336, LOC109731317

GCF_000247795.1: LOC109554833, LOC109555838, LOC109555536, LOC109557325, LOC109557874, LOC109557873, LOC109558174, LOC109557872, LOC109558480, LOC109558334, LOC109559994, LOC109562474, LOC109562225, LOC109564132, LOC109564551, LOC109564364, LOC109564590, LOC109565844, LOC109567781, LOC109568235, LOC109569046, LOC109569087, LOC109569045, LOC109570262, LOC109571822, LOC109577282, LOC109578007

GCF_000258655.2: LOC106634471, LOC106635360, LOC106635266, LOC100976750

GCF_000264685.3: LOC108582303, LOC108585878, LOC108586550, LOC110741080, LOC103877537, LOC110741228, LOC108582238, LOC108583105, LOC103880168, LOC110742390, LOC108584642, LOC108584956, LOC110742783, LOC110742808, LOC108585969, LOC110743584, LOC110743693, LOC103886387

GCF_000298735.2: LOC105602254, LOC105602646, LOC105603621, LOC105604082, LOC105605555, LOC105605728, LOC105608895, LOC105613207, LOC105614711, LOC105614635, LOC105615508, LOC105615734, LOC105615865, LOC105615893, LOC105616107, LOC105616289, LOC105611820, LOC105616610, LOC105616742, LOC105615685, LOC105611746, LOC106990898, LOC105605056, LOC106990533, LOC106990894, LOC106990992, LOC106991000, LOC105614903, LOC105612099, LOC106990607, LOC105615382, LOC105615065, LOC105613453, LOC106991203, LOC105615805, LOC106991207, LOC105615953, LOC105616123, LOC106991450, LOC105616776, LOC101108945, LOC105602979, LOC106991649, LOC106991751, LOC106991725, LOC106991684, LOC101108432, LOC106991794, LOC105604166, LOC105604795, LOC105605676, LOC106991968, LOC106991976, LOC106990624

GCF_000306695.2: LOC105369972, LOC105372269, LOC107984745, LOC105373926, LOC107983994, LOC107986987, LOC107986724, LOC105374013, LOC105376526, LOC107985956, LOC107984264, LOC107986062, LOC107984203, LOC107986860

GCF_000317375.1: LOC101982089, LOC106143758, LOC102000421, LOC101980249, LOC106144010, LOC106144313, LOC102002969, LOC106144224, LOC106144419, LOC101993120, LOC113455526, LOC101980986, LOC101998285, LOC106144495, LOC113457334, LOC113457408, LOC101988739, LOC101998541, LOC106144280, LOC101998829, LOC102000399

GCF_000364345.1: LOC107126576, LOC107126573, LOC107126667, LOC107126666, LOC107126659, LOC107126965, LOC107127030, LOC107127299, LOC107127512, LOC107127566, LOC107127925, LOC107128502, LOC107128989, LOC107129267, LOC102124810, LOC102129186, LOC107129375, LOC107130507, LOC107130565, LOC107130829, LOC107130828

GCF_000772875.2: LOC106992905, LOC106993115, LOC106993451, LOC106994335, LOC106994511, LOC106994762, LOC106995226, LOC106995264, LOC106995412, LOC106995613, LOC106995685, LOC106997384, LOC106997531, LOC106997535, LOC106998453, LOC106999404, LOC106999601, LOC107000104, LOC107000137

GCF_000803125.2: LOC105090048, LOC116156322, LOC116157823

GCF_001704415.2: LOC106502104, LOC106502327, LOC108633770, LOC102177135, LOC108634447, LOC108634321, LOC102182527, LOC108635625, LOC108635605, LOC108635662, LOC108635654, LOC108635898, LOC108636107, LOC108636081, LOC108636278, LOC108636266, LOC108636255, LOC108636420, LOC102181916, LOC108636423, LOC108636659, LOC108636661, LOC108636657, LOC108636662, LOC108636665, LOC108636591, LOC108636663, LOC108636660, LOC108636664, LOC108637087, LOC108637287, LOC106502793, LOC108637619, LOC106502965, LOC108637882, LOC108637988, LOC108638071, LOC108638080, LOC108638207

GCF_002007445.2: LOC105241688

GCF_002201575.2: LOC110574818, LOC110583691, LOC123323884, LOC123323996, LOC123324002

GCF_002263795.3: LOC100848171, LOC100848463, LOC104970693, LOC104973175, LOC104973030, LOC112443209, LOC112443207, LOC112443452, LOC112444529, LOC104975936, LOC112445578, LOC112445423, LOC107132928, LOC132342381, LOC132342279, LOC132342764, LOC788150, LOC132342722, LOC787858, LOC132342891, LOC112443213, LOC132343336, LOC112443502, LOC132343538, LOC132343464, LOC132343737, LOC132343927, LOC104976020, LOC132344115, LOC132344125, LOC132344315, LOC101905248, LOC132344308, LOC132344357, LOC132344801, LOC132344287, LOC520016, LOC132344276, LOC112445540, LOC132344760, LOC132344980, LOC132345173, LOC112446473, LOC107131684, LOC132345324, LOC132345399, LOC104970926, LOC104969531, LOC132346306, LOC132346771, LOC132346538, LOC132346751, LOC789027, LOC132346927

GCF_002742125.1: LOC100527962, LOC105616742, LOC114109035, LOC114109394, LOC114110084, LOC114110071, LOC114110281, LOC114112647, LOC105604082, LOC114112492, LOC106991976, LOC114111711, LOC106990624, LOC114112539, LOC105608895, LOC114108696, LOC114113743, LOC114113736, LOC105602254, LOC114114035, LOC114114034, LOC106990358, LOC114115259, LOC114115257, LOC114115227, LOC114114904, LOC114115797, LOC114115778, LOC106991586, LOC114115771, LOC114116607, LOC106990188, LOC114117237, LOC105613629, LOC114118022, LOC114117898, LOC101108945, LOC114108716, LOC106991684

GCF_002776525.5: LOC111525929, LOC111537057, LOC111539520, LOC111543135, LOC113221538, LOC113224797

GCF_002837175.3: LOC112064783, LOC114486455

GCF_002863925.1: LOC111769050, LOC111770878, LOC106781350, LOC111771462, LOC111772137, LOC111774979, LOC111775724, LOC111771471

GCF_002880775.1: LOC112128828, LOC112133793, LOC112134291

GCF_003121395.1: LOC112577984, LOC112577983, LOC112577982, LOC112578776, LOC112578885, LOC112578886, LOC102414225, LOC112579605, LOC112579371, LOC112579731, LOC112579735, LOC112581737, LOC102400673, LOC112582030, LOC112582600, LOC112582649, LOC112582625, LOC112582836, LOC112582601, LOC112583534, LOC112582991, LOC102397332, LOC112577753, LOC112584366, LOC102392518, LOC112585049, LOC112585053, LOC112585535, LOC112586107, LOC102391948, LOC112587297, LOC112587558, LOC112587825, LOC112587962

GCF_003254725.2: LOC112674797, LOC112675532, LOC118353763, LOC112641869, LOC112654297, LOC125752886, LOC112668619, LOC112669204, LOC118354390, LOC118352421, LOC112679158, LOC118350339, LOC112650405

GCF_003255815.1: LOC112628263

GCF_003339765.1: LOC106993451, LOC106994511, LOC106995685, LOC106995412, LOC107000104, LOC114669926, LOC114670950, LOC114670951, LOC114671698, LOC114672644, LOC114674100, LOC114675385, LOC114677579, LOC114677521, LOC721374, LOC114677519, LOC114680147

GCF_003369695.1: LOC113876258, LOC113877692, LOC113877364, LOC113877423, LOC113878365, LOC113879794, LOC113880709, LOC113880416, LOC113882588, LOC113882891, LOC113884411, LOC113884409, LOC113884515, LOC113884549, LOC113885190, LOC113885836, LOC113887467, LOC113887975, LOC113887662, LOC113888091, LOC113889193, LOC113890844, LOC113891289, LOC113892432, LOC113893807, LOC113893811, LOC113893589, LOC113895134, LOC113894801, LOC113896057, LOC113896650, LOC113896405, LOC113897038, LOC113896404, LOC113898701, LOC113899324, LOC113899815, LOC113899355, LOC113899551, LOC113900310, LOC113900364, LOC113900030, LOC113901335, LOC113904878, LOC113906043

GCF_003668045.3: LOC113832278, LOC113832502, LOC113832446, LOC113832559, LOC107980128, LOC100771383, LOC113832873, LOC113832822, LOC113832706, LOC113832753, LOC113832899, LOC113832901, LOC113832852, LOC113832785, LOC113833083, LOC100771342, LOC113833204, LOC113833203, LOC113833581, LOC113834019, LOC113834242, LOC113834239, LOC103160953, LOC113834150, LOC113834149, LOC113834362, LOC113834409, LOC113834420, LOC113834356, LOC113834411, LOC113834353, LOC113834484, LOC113834501, LOC107980386, LOC113834500, LOC113834687, LOC113834856, LOC113835045, LOC113835009, LOC113835041, LOC113835284, LOC113835176, LOC113835459, LOC113835292, LOC113835330, LOC113835489, LOC113835892, LOC113835856, LOC113835851, LOC113835995, LOC113835932, LOC113836208, LOC113836206, LOC113836300, LOC113836409, LOC113836537, LOC113836723, LOC113836825, LOC113836798, LOC113837013, LOC113837033, LOC113837321, LOC113837614, LOC113837550, LOC113837405, LOC113837528, LOC113837661, LOC113838392, LOC113838806, LOC113838162, LOC113837704, LOC113837702, LOC107980247, LOC113838604, LOC118238257, LOC118237743, LOC118238197, LOC118238207, LOC113833979, LOC113838961, LOC113833560, LOC118238354, LOC113834352, LOC113834164, LOC113835124, LOC113834740, LOC118238449, LOC103162656, LOC103164217, LOC118238540, LOC118238570, LOC113835055, LOC113835669, LOC118238844, LOC118238745, LOC113835850, LOC113835852, LOC118238940, LOC118239113, LOC113836465, LOC118239311, LOC118239263, LOC107978387, LOC118239406, LOC118239448, LOC118239489, LOC113832931, LOC118239520, LOC113832936, LOC113833395, LOC118239561, LOC118239572, LOC113832243, LOC113832329, LOC118239691, LOC118239699, LOC118239639, LOC113832398, LOC118239789, LOC113839062

GCF_003704035.1: LOC102907425, LOC107400922, LOC107401749, LOC107402015, LOC121821425, LOC121823529, LOC107401958, LOC102906164, LOC102904977, LOC121825611, LOC121825612, LOC121825602, LOC102925565, LOC102911229, LOC102906111, LOC102909354, LOC102918559, LOC121826803, LOC121826702, LOC121826345, LOC107402471, LOC121826589, LOC121828709, LOC121829188, LOC102928552, LOC121831503, LOC121831685, LOC121832656

GCF_004115265.2: LOC117014441, LOC117014375, LOC117015174, LOC117015168, LOC117017314, LOC117017358, LOC117018879, LOC117022082, LOC117022118, LOC117022619, LOC117027140, LOC117029760, LOC117029648, LOC117029885, LOC117031540, LOC117032036, LOC117033713, LOC117033701, LOC117034204, LOC117034947, LOC117035007, LOC117035448, LOC117036718

GCF_004126475.2: LOC114497143, LOC114508797, LOC114508976

GCF_004664715.2: LOC114680714, LOC114682222, LOC114684040, LOC114683789, LOC114683711, LOC114684968, LOC114688875, LOC114692502, LOC114692408, LOC114693335, LOC114693949, LOC114695582, LOC114698879, LOC114698178, LOC114699569, LOC114699795, LOC114701742, LOC114703675, LOC114704133, LOC114704254, LOC114708416, LOC114708592, LOC114710432, LOC114694925, LOC119086371, LOC114684970, LOC119086569, LOC114683585, LOC119086648, LOC119087372, LOC114693482, LOC119088111, LOC114706309, LOC119088213, LOC114709616, LOC119088608, LOC114689465, LOC114684244, LOC119088988, LOC119088810, LOC119089164, LOC119089130, LOC119089253

GCF_005444595.1: LOC102151484, LOC119871300, LOC106558846, LOC119872251, LOC119872662, LOC106559386, LOC111097969, LOC119874041, LOC119874017, LOC119874254, LOC119869212, LOC100688839, LOC102155235, LOC119864608, LOC111092249, LOC111093267, LOC119875562, LOC119875589

GCF_006229205.1: LOC115274686, LOC115277519, LOC115278501, LOC115278806, LOC115283423, LOC115284895, LOC115291102, LOC115290627, LOC115291151, LOC115293430, LOC115295278, LOC115305296

GCF_006542625.1: LOC115831010, LOC115834471

GCF_007474595.2: LOC115499676, LOC115500365, LOC115500706, LOC115506065, LOC115506732, LOC115506997, LOC115508113, LOC115510386, LOC115510316, LOC115510674, LOC115512811, LOC115512942, LOC115514128, LOC115514603, LOC115516974, LOC115518727, LOC115518377, LOC115521030, LOC115523707, LOC115523804, LOC115524810, LOC115526218, LOC115526206, LOC115526354, LOC115526215, LOC115526217, LOC115527285, LOC115527303, LOC116737703, LOC115502108, LOC115501508, LOC116737870, LOC115518618, LOC116738226, LOC116738225, LOC115519903, LOC115519730, LOC115528068, LOC115525749, LOC115525460, LOC115499098, LOC115522438

GCF_007565055.1: LOC115892130, LOC115894575, LOC115894534, LOC115896518, LOC115896978, LOC115898283, LOC115899059, LOC115899162, LOC115899640, LOC115900080, LOC115900695

GCF_008122165.1: LOC109028578, LOC115934041, LOC115934952, LOC115934976, LOC115936058

GCF_008632895.1: LOC116067887, LOC116067864, LOC116070982, LOC116074490, LOC116074472, LOC116077184, LOC116081035, LOC116081102, LOC116082628, LOC116083312, LOC116083610, LOC116085231, LOC116086244, LOC116089775, LOC116089498, LOC116091696, LOC116093336, LOC116093243, LOC116095272, LOC116094893, LOC116094181, LOC116095258, LOC116096562, LOC116097633, LOC116099877, LOC116101293, LOC116104577

GCF_008692025.1: LOC116739062, LOC116739584, LOC116741924, LOC116741954, LOC116742307, LOC116742927, LOC116746708, LOC116747173, LOC116747283, LOC116746896, LOC116747182, LOC116747129, LOC116746963, LOC116746964, LOC116747280, LOC116747061, LOC116747337, LOC116747543, LOC116747545, LOC116748340, LOC116747970, LOC116748447, LOC116748914, LOC116749583, LOC116750708, LOC116750676, LOC116750679, LOC116750680, LOC116750678, LOC116751076, LOC116750896, LOC116750979, LOC116751003, LOC116751215, LOC116751940, LOC116753927, LOC116753552, LOC116756123, LOC116756136, LOC116756376, LOC116757431, LOC116758282, LOC116758284, LOC116759162, LOC116762933, LOC116764021, LOC116764045, LOC116764374, LOC116764994, LOC116764971

GCF_008728515.1: LOC108582303, LOC110741080, LOC110741228, LOC108583947, LOC108584956, LOC103886387, LOC108581122, LOC103877537, LOC116270097, LOC116273843, LOC116274523, LOC116275277, LOC101018055, LOC116275278

GCF_009762305.2: LOC113919229, LOC113922838, LOC113922837, LOC113926887, LOC113929887, LOC113931444, LOC113934135, LOC118356104, LOC118356183, LOC118356315, LOC118356351, LOC118356743, LOC118356773, LOC118356788, LOC118357115, LOC118357181

GCF_009806435.1: LOC100351960, LOC103347227, LOC103351067, LOC100352200, LOC108176200, LOC108175591, LOC108176921, LOC108178205, LOC103350567, LOC108178888, LOC108177987, LOC127482832, LOC103351040, LOC103350680, LOC103351068, LOC103346967, LOC100350684, LOC127484455, LOC127484850, LOC108178684, LOC108178319, LOC127485612, LOC127485945, LOC127486816, LOC127486535, LOC127487098, LOC100347275, LOC108175598, LOC103345324, LOC103345346, LOC127488070, LOC127488345, LOC103345965, LOC127489089, LOC108175969, LOC108176401, LOC100352752, LOC127491615, LOC103348625, LOC108177122, LOC108177250, LOC108177361, LOC100356118, LOC127493742

GCF_009829155.1: LOC116568178, LOC116568766, LOC116568757, LOC116570493, LOC116571500, LOC116577974, LOC116577985, LOC116578859, LOC116580025, LOC116581447, LOC116582276, LOC116582246, LOC116582302, LOC116582756, LOC116583488, LOC116583937, LOC116583578, LOC116583967, LOC116584630, LOC116585765, LOC116587206, LOC116587276, LOC116587269, LOC116587231, LOC116587221, LOC116587275, LOC116587277, LOC116589423, LOC116589313, LOC116590063, LOC116589471, LOC116589462, LOC116589801, LOC116590868, LOC116590832, LOC116591697, LOC116593508, LOC116593527, LOC116596795, LOC116597083

GCF_009834535.1: LOC116656732, LOC116662473

GCF_009873245.2: LOC118885471, LOC118892053


In [9]:
DigitisInRowThreshold

[1] 4

In [10]:
length(unique(DFtoWrite$accession))

[1] 170

In [11]:
nrow(DFtoWrite)

[1] 5280

In [12]:
DFtoWrite[ !grepl(pattern = "LOC", x = DFtoWrite$gene),]

     accession gene

In [13]:
# run once
if ("suspectedTEgenes" %in% dbListTables(mydbRW)) dbExecute(mydbRW, 'DROP TABLE suspectedTEgenes')
dbWriteTable(mydbRW, "suspectedTEgenes", DFtoWrite, append=FALSE)
dbExecute(mydbRW, 'CREATE INDEX IF NOT EXISTS suspectedTEgenesAccessionInd ON suspectedTEgenes(accession, gene)')
dbExecute(mydbRW, 'CREATE INDEX IF NOT EXISTS suspectedTEgenesGeneInd ON suspectedTEgenes(gene, accession)')

[1] 0

[1] 0

# Index FastA files to estimate number of Ns in the future

In [14]:
swarmlines=NULL
sbatchscript="~/data/lambda/notebooks/Multigene.Step3.IndexFasta.sh"

for (accession in unique(GenomesDF$accession)){
    # find genomic fasta file
    accessionDir=paste0(StaticInpDir,accession,"/")
    filepattern=paste0(accession,".*_genomic.fna$")
    fs=list.files(accessionDir, pattern = filepattern, full.names = TRUE)
    if (length(fs)!=1){
        message("Problem with ", accession, " Not a single ref genome file")
        break
    }
    swarmlines=addToVec(swarmlines, paste(sbatchscript, fs))
}

In [15]:
length(swarmlines)

[1] 223

In [16]:

swarmparams=paste0("#SWARM -t 8 -g 20 --time=2:00:00 --gres=lscratch:20 --logdir ", path.expand(OutputDir),"/slurm_logs/")
maxchunk=1000
timestamp=getTimeStamp()
processed=0
i=0
swarmFiles=NULL
while (processed<length(swarmlines)){
    upperlimit=processed+min(maxchunk, length(swarmlines)-processed)
    message(paste(processed+1, upperlimit))
    fname=paste0(OutputDir,"/runningIndexingFastAfiles.",i,"-", timestamp,".swarm")
    writeLines(text = c(swarmparams, swarmlines[(processed+1):upperlimit]), 
               con=fname)
    message("Run from bash: ", fname)
    swarmFiles=addToVec(swarmFiles, fname)
    processed=upperlimit
    i=i+1
}

1 223

Run from bash: ~/data/lambda/output//runningIndexingFastAfiles.0-2026-01-15_09.36.44.820386.swarm